name: yugam_radio
description: An Internet Radio.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  avatar_glow: ^2.0.2
  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.7
  volume_controller: ^2.0.4
  audio_service: ^0.18.7
  rxdart: ^0.27.5
  url_launcher: ^6.0.0
  connectivity_plus: ^3.0.2
  flutter_offline: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.14

flutter_native_splash:
  color: "#141C27"
  image: "assets/images/logo.png"
  android: true
  ios: true
  web: false

flutter_icons:
  image_path: "assets/images/logo.png" 
  android: true
  ios: true
  web:
    generate: false
    image_path: "assets/images/logo.png"
    background_color: "#141C27"
    theme_color: "#141C27"
  windows:
    generate: false
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
